name: Deploy to Server

on:
  push:
    branches:
      - main ## main에 merge시에 트리거 발동

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      env:
        SSH_HOST: ${{ secrets.EC2_SSH_HOST }}
        SSH_USER: ${{ secrets.EC2_SSH_USER }}
        SSH_PORT: ${{ secrets.EC2_SSH_PORT }}
      run: |
        ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST 'cd ~/BlindDateBE && git pull'